# hit@1 = 0.5385
batch_size: 9
batch_size_dev: 8
beta: 0.06985519544113815
cached_QAMetaData_path: "./.cache/itl/kinship_hinton_qa_3hop.json"
data_dir: "data/KinshipHinton"
epochs: 17
learning_rate: 0.00109082
model: "TransE"
nav_epsilon_error: 1
nav_epsilon_metric: "l2"
nav_start_emb_type: "relevant"
node_data_key: ""
node_data_path: ""
num_rollout_steps: 3
num_rollouts: 16
preferred_config: ""
raw_QAData_path: "data/KinshipHinton/kinship_hinton_qa_3hop.csv"
relationship_data_key: ""
relationship_data_path: ""
rl_gamma: 0.9432724080297948
seed: 420
supervised_adapter_scalar: 0.001136
supervised_expected_sigma: 0.000003
supervised_noise_scale: 0.000003
supervised_sigma_scalar: 0.000002
trained_model_path: "models/TransE_KinshipHinton_dim12"
use_ann_reward: true