program: kge_launcher.py
project: kinship-hinton
method: grid

command:
  - python
  - kge_launcher.py

metric:
  name: Valid_HITS@1  # (higher is better)
  goal: maximize  # Higher is better

parameters:
  mode:
    value: train

  model:
    value: TransE

  dataset:
    value: KinshipHinton

  gpu_id:
    value: 0

  seed:
    values: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

  batch_size:
    value: 18

  negative_sample_size:
    value: 14

  hidden_dim:
    value: 10

  gamma:
    value: 3.0679463664224995

  alpha:
    value: 0.467321526426271

  learning_rate:
    value: 0.000507328572652022

  max_steps:
    value: 70000

  test_batch_size:
    value: 16

  wandb_project:
    value: kinship-hinton  # Your wandb project name

  track:
    value: true  # Always track with wandb

  saving_metric:
    value: HITS@1  # Metric to save the best model
  
  saving_threshold:
    value: 0.85  # Threshold for saving the best model

  additional_params:
    value: ""  # Empty unless you add extra flags like -de, -dr
