adversarial_temperature: 0.9059047511316708
batch_size: 7
clean_up: true
countries: false
cuda: true
data_path: "data/KinshipHinton"
do_test: true
do_train: false # set to false if loading a pretrained model
do_valid: true
double_entity_embedding: false
double_relation_embedding: false
evaluate_train: false
freeze_entities: false
freeze_relationship: false
full_graph: false
gamma: 3.0270593905904852
hidden_dim: 10
lambda_lp: 0.4480686953051138
lambda_rp: 0.3983648182624783
learning_rate: 0.00058
log_steps: 100
max_steps: 200000
model: "TransE"
negative_adversarial_sampling: true
negative_sample_size: 14
random_seed: 0
save_checkpoint_steps: 10000
save_path: "models/TransE_KinshipHinton_dim10_20250809_114609"
saving_metric: "HITS@1"
saving_threshold: 0.8
task: "basic"
test_batch_size: 16
test_log_steps: 1000
timestamp: "20250809_114609"
track: false
uni_weight: false
valid_steps: 5000
wandb_project: "kinship-hinton"
warm_up_steps: null
# init_checkpoint: "models/TransE_KinshipHinton_dim10_full" # uncomment this line to load a checkpoint instead of training from scratch